
modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
# The modid of the mod
modId="relivedmobs"
# Version of the Mod
version="0.1.0"
displayName="Relived Mobs"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="relivedmobs.png"
credits="Thanks for this example mod goes to Java"
authors="YeoXuHang & Heizer"
description='''A Mod aming to enhance your Minecraft World by adding new Mobs, Structures and a lot more in the Future!
'''
[[dependencies.relivedmobs]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.relivedmobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
